development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: dfg5p5jvpi06ip
  username: rkuqzzowoocfqp
  password: Jlx4Lb_Fb7kqxemY_K5ilrjDhd
  host: ec2-54-197-249-212.compute-1.amazonaws.com